INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (1, 4, 0, 'AFGANISTAN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (2, 8, 0, 'ALBANIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (3, 276, 1, 'ALEMANIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (4, 20, 0, 'ANDORRA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (5, 24, 0, 'ANGOLA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (6, 660, 0, 'ANGUILA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (7, 28, 0, 'ANTIGUA Y BARBUDA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (8, 530, 0, 'ANTILLAS NEERLANDESAS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (9, 682, 0, 'ARABIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (10, 12, 0, 'ARGELIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (11, 32, 0, 'ARGENTINA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (12, 533, 0, 'ARUBA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (13, 36, 2, 'AUSTRALIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (14, 40, 3, 'AUSTRIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (15, 31, 0, 'AZERBAIYAN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (16, 44, 0, 'BAHAMAS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (17, 48, 0, 'BAHREIN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (18, 50, 0, 'BANGLADESH');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (19, 52, 0, 'BARBADOS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (20, 56, 4, 'BELGICA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (21, 84, 0, 'BELICE');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (22, 204, 0, 'BENIN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (23, 60, 0, 'BERMUDAS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (24, 112, 0, 'BIELORRUSIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (25, 68, 0, 'BOLIVIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (26, 70, 0, 'BOSNIA HERZEGOBINA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (27, 72, 0, 'BOTSWANA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (28, 76, 33, 'BRASIL');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (29, 96, 0, 'BRUNEI DARUSSALAM');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (30, 100, 41, 'BULGARIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (31, 854, 0, 'BURKINA FASO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (32, 108, 0, 'BURUNDI');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (33, 64, 0, 'BUTAN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (34, 132, 0, 'CABO VERDE');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (35, 116, 0, 'CAMBOYA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (36, 120, 0, 'CAMERUN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (37, 124, 5, 'CANADA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (38, 136, 0, 'CAYMAN ISLANDS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (39, 148, 0, 'CHAD');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (40, 203, 0, 'CHECOSLOVAQUIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (41, 152, 39, 'CHILE');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (42, 156, 34, 'CHINA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (43, 196, 23, 'CHIPRE');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (44, 170, 42, 'COLOMBIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (45, 174, 0, 'COMORAS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (46, 178, 0, 'CONGO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (47, 36, 43, 'COREA DEL SUR');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (48, 384, 0, 'COSTA DE MARFIL');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (49, 188, 0, 'COSTA RICA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (50, 191, 0, 'CROACIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (51, 192, 0, 'CUBA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (52, 208, 6, 'DINAMARCA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (53, 212, 0, 'DOMINICA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (54, 218, 0, 'ECUADOR');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (55, 818, 0, 'EGIPTO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (56, 222, 0, 'EL SALVADOR');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (58, 232, 0, 'ERITREA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (59, 703, 24, 'ESLOVAQUIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (60, 705, 25, 'ESLOVENIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (61, 724, 7, 'ESPAÑA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (62, 336, 0, 'ESTADO DE LA CIUDAD DEL VATICANO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (63, 840, 8, 'ESTADOS UNIDOS DE NORTEAMERICA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (64, 233, 26, 'ESTONIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (65, 231, 0, 'ETIOPIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (66, 643, 0, 'FEDERACION RUSA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (67, 608, 0, 'FILIPINAS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (68, 246, 9, 'FINLANDIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (69, 242, 0, 'FIYI');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (70, 250, 10, 'FRANCIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (71, 266, 0, 'GABON');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (72, 270, 0, 'GAMBIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (73, 268, 0, 'GEORGIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (74, 288, 0, 'GHANA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (75, 292, 0, 'GIBRALTAR');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (76, 308, 0, 'GRANADA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (77, 300, 11, 'GRECIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (78, 304, 0, 'GROENLANDIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (79, 312, 0, 'GUADALUPE');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (80, 316, 0, 'GUAM');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (81, 320, 0, 'GUATEMALA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (82, 254, 0, 'GUAYANA FRANCESA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (83, 324, 0, 'GUINEA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (84, 624, 0, 'GUINEA BISSAU');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (85, 226, 0, 'GUINEA ECUATORIAL');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (86, 328, 0, 'GUYANA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (87, 332, 0, 'HAITI');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (88, 528, 0, 'HOLANDA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (89, 340, 0, 'HONDURAS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (90, 36, 13, 'HONG KONG');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (91, 348, 27, 'HUNGRIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (92, 356, 35, 'INDIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (94, 826, 0, 'INGLATERRA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (95, 368, 0, 'IRAK');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (96, 364, 0, 'IRAN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (97, 372, 14, 'IRLANDA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (98, 162, 0, 'ISLA DE NAVIDAD');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (99, 570, 0, 'ISLA NIUE');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (100, 574, 0, 'ISLA NORFOLK');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (101, 352, 44, 'ISLANDIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (102, 166, 0, 'ISLAS COCOS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (103, 184, 0, 'ISLAS COOK');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (104, 234, 0, 'ISLAS FEROE');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (105, 239, 0, 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (106, 238, 0, 'ISLAS MALVINAS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (107, 580, 0, 'ISLAS MARIANAS DEL NORTE');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (108, 584, 0, 'ISLAS MARSHALL');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (109, 612, 0, 'ISLAS PITCAIRN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (110, 90, 0, 'ISLAS SALOMON');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (111, 744, 0, 'ISLAS SVALBARD Y JAN MAYEN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (112, 796, 0, 'ISLAS TURCAS Y CAICOS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (113, 92, 0, 'ISLAS VIRGENES BRITANICAS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (114, 850, 0, 'ISLAS VIRGENES ESTADOUNIDENSES');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (115, 876, 0, 'ISLAS WALLIS Y FUTUNA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (116, 376, 40, 'ISRAEL');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (117, 380, 15, 'ITALIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (118, 388, 0, 'JAMAICA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (119, 392, 16, 'JAPON');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (120, 832, 0, 'JERSEY');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (121, 400, 0, 'JORDANIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (122, 447, 0, 'KASAJISTAN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (123, 404, 0, 'KENIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (124, 417, 0, 'KIRGUISTAN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (125, 296, 0, 'KIRIBATI');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (126, 408, 0, 'KOREA DEL NORTE');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (127, 410, 0, 'KOREA DEL SUR');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (128, 414, 0, 'KUWAIT');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (129, 418, 0, 'LAOS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (130, 426, 0, 'LESOTHO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (131, 428, 28, 'LETONIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (132, 422, 0, 'LIBANO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (133, 430, 0, 'LIBERIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (134, 434, 0, 'LIBIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (135, 438, 0, 'LIECHTENSTEIN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (136, 36, 29, 'LITUANIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (137, 442, 17, 'LUXEMBURGO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (138, 446, 0, 'MACAO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (139, 807, 0, 'MACEDONIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (140, 450, 0, 'MADAGASCAR');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (141, 458, 47, 'MALASIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (142, 454, 0, 'MALAWI');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (143, 462, 0, 'MALDIVAS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (144, 466, 0, 'MALI');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (145, 470, 30, 'MALTA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (146, 504, 0, 'MARRUECOS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (147, 474, 0, 'MARTINICA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (148, 480, 0, 'MAURICIO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (149, 478, 0, 'MAURITANIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (93, 360, 55, 'INDONESIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (150, 175, 0, 'MAYOTTE');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (151, 484, 18, 'MEXICO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (152, 583, 0, 'MICRONESIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (153, 498, 0, 'MOLDAVIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (154, 492, 0, 'MONACO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (155, 496, 0, 'MONGOLIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (156, 500, 0, 'MONTSERRAT');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (157, 508, 0, 'MOZAMBIQUE');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (158, 104, 0, 'MYANMAR');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (159, 516, 0, 'NAMIBIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (160, 520, 0, 'NAURU');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (161, 524, 0, 'NEPAL');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (162, 558, 0, 'NICARAGUA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (163, 562, 0, 'NIGER');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (164, 566, 0, 'NIGERIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (165, 578, 38, 'NORUEGA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (166, 540, 0, 'NUEVA CALEDONIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (167, 554, 48, 'NUEVA ZELANDA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (168, 512, 0, 'OMAN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (169, 36, 36, 'OTRO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (170, 36, 12, 'PAISES BAJOS (HOLANDA)');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (171, 585, 0, 'PALAOS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (172, 591, 0, 'PANAMA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (173, 598, 0, 'PAPUA NUEVA GUINEA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (174, 586, 0, 'PAQUISTAN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (175, 600, 0, 'PARAGUAY');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (176, 604, 45, 'PERU');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (177, 258, 0, 'POLINESIA FRANCESA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (178, 616, 19, 'POLONIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (179, 620, 20, 'PORTUGAL');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (180, 630, 0, 'PUERTO RICO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (181, 634, 0, 'QATAR');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (182, 0, 0, 'R03 E -0304 Y E -0305');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (183, 36, 21, 'REINO UNIDO DE LA GRAN BRETAÑA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (184, 140, 0, 'REP. CENTRO AFRICANA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (185, 36, 31, 'REPUBLICA CHECA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (186, 51, 0, 'REPUBLICA DE ARMENIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (187, 440, 0, 'REPUBLICA DE LITUANIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (188, 674, 0, 'REPUBLICA DE SAN MARINO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (189, 262, 0, 'REPUBLICA DE YIBUTI');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (190, 180, 0, 'REPUBLICA DEMOCRATICA DEL CONGO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (191, 214, 0, 'REPUBLICA DOMINICANA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (192, 638, 0, 'REUNION');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (193, 646, 0, 'RUANDA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (194, 642, 37, 'RUMANIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (195, 732, 0, 'SAHARA OCCIDENTAL');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (196, 882, 0, 'SAMOA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (197, 16, 0, 'SAMOA AMERICANA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (198, 659, 0, 'SAN CRISTOBAL Y NIEVES');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (199, 666, 0, 'SAN PEDRO Y MIQUELON');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (200, 670, 0, 'SAN VICENTE Y LAS GRANADINAS');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (201, 654, 0, 'SANTA HELENA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (202, 662, 0, 'SANTA LUCIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (203, 678, 0, 'SANTO TOME Y PRINCIPE');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (204, 686, 0, 'SENEGAL');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (205, 688, 0, 'SERBIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (206, 690, 0, 'SEYCHELLES');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (207, 694, 0, 'SIERRA LEONA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (208, 702, 46, 'SINGAPUR');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (209, 760, 0, 'SIRIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (210, 706, 0, 'SOMALIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (211, 144, 0, 'SRI LANKA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (212, 710, 0, 'SUD AFRICA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (213, 36, 49, 'SUDAFRICA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (214, 736, 0, 'SUDAN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (215, 752, 32, 'SUECIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (216, 756, 22, 'SUIZA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (217, 740, 0, 'SURINAM');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (218, 748, 0, 'SWAZILANDIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (219, 764, 50, 'TAILANDIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (220, 158, 51, 'TAIWAN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (221, 834, 0, 'TANZANIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (222, 762, 0, 'TAYIKISTAN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (223, 86, 0, 'TERRITORIO BRITANICO DEL OCEANO INDICO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (224, 260, 0, 'TERRITORIOS AUSTRALES FRANCESES');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (225, 626, 0, 'TIMOR ORIENTAL');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (226, 768, 0, 'TOGO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (227, 772, 0, 'TOKELAU');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (228, 776, 0, 'TONGA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (229, 631, 0, 'TRINIDAD Y TOBAGO');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (230, 788, 0, 'TUNEZ');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (231, 795, 0, 'TURKMENISTAN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (232, 792, 0, 'TURQUIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (233, 798, 0, 'TUVALU');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (234, 435, 0, 'UCRANIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (235, 800, 0, 'UGANDA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (236, 858, 0, 'URUGUAY');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (237, 860, 0, 'UZBEKISTAN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (238, 548, 0, 'VANUATU');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (239, 862, 0, 'VENEZUELA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (240, 704, 0, 'VIETNAM');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (241, 887, 0, 'YEMEN');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (242, 894, 0, 'ZAMBIA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (243, 716, 0, 'ZIMBABWE');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (244, 0, 53, 'ARABIA SAUDITA');
INSERT INTO public.cat_paises (id_pais, id_cnbv, id_consar, descripcion) VALUES (57, 784, 54, 'EMIRATOS ARABES UNIDOS');
